default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: buybye-dev

test:
  <<: *default
  database: buybye-test

production:
  <<: *default
  database: buybye-pro
