development:
  secret_key_base: 4b9b217a7f7ff221df5e689fe8a1a0193b2a8520915798736a1d208dbc5b1d9ef61995a3e8a844f3e4625ee59a04faa36fa35cd7791cbb9f2725f4f04e9eda18
  slack_webhook_url: https://hooks.slack.com/services/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
  google_recaptcha_site_key: 6LfajgkUAAAAACKWaIny6gWGAlDT6EQD4o30Fr0b
  google_recaptcha_secret_key: 6LfajgkUAAAAAMnamTLxX072bwH58gYAyvF1taMu
test:
  secret_key_base: 0ec7d50cb1d96f54b88e1048b170e85159fc312cda4303470ec207040eb829d35517b57f891b0b7554f6e2f51bc97129bd7dcf434c00d7dee40dce72daac01da
  slack_webhook_url: https://hooks.slack.com/services/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
  google_recaptcha_site_key: 6LfajgkUAAAAACKWaIny6gWGAlDT6EQD4o30Fr0b
  google_recaptcha_secret_key: 6LfajgkUAAAAAMnamTLxX072bwH58gYAyvF1taMu

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack_webhook_url: https://hooks.slack.com/services/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
  google_recaptcha_site_key: 6LfajgkUAAAAACKWaIny6gWGAlDT6EQD4o30Fr0b
  google_recaptcha_secret_key: 6LfajgkUAAAAAMnamTLxX072bwH58gYAyvF1taMu
